---
# tasks file for slave
- name: configure yum repo for docker
  copy:
    src: /root/task-28/slave/files/docker.repo
    dest: /etc/yum.repos.d/docker.repo

- name: install docker 
  command: yum install docker-ce --nobest -y

- name: start and enable docker
  service:
          name: docker
          state: started
          enabled: yes
 
- name: configure yum repo for kubernetes 
  copy: 
    src: /root/task-28/slave/files/kubernetes.repo 
    dest: /etc/yum.repos.d/kubernetes.repo 
 
- name: install kubeadm kubelet and kubectl 
  command: yum install kubeadm kubelet kubectl -y

- name: start and enable kubelet service 
  service: 
    name: kubelet 
    state: started 
    enabled: yes  

- name: configure docker driver
  copy:
    src: /root/task-28/slave/files/daemon.json
    dest: /etc/docker/daemon.json

- name: restart docker
  service:
          name: docker
          state: restarted
 
- name: configure iptables 
  copy: 
    src: /root/task-28/slave/files/k8s.conf 
    dest: /etc/sysctl.d/k8s.conf 

- name: restart service
  shell: sudo sysctl --system
  ignore_errors: yes

- name: join slave to master node
  shell: "{{ master_token }}"
  ignore_errors: yes 
  register: masterToken 

- debug:
    var: masterToken.stdout_lines
